import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { PayrollRecord } from '@/store/usePayrollStore';
import { COMPANY_NAME, APP_NAME } from '@/utils/constants';

// Extend jsPDF type to include autoTable
interface jsPDFWithAutoTable extends jsPDF {
    lastAutoTable: { finalY: number };
}

export const PDFGenerator = {
    generatePayslip: (record: PayrollRecord, isPreview: boolean = false): string | void => {
        const doc = new jsPDF() as jsPDFWithAutoTable;

        // Header
        doc.setFontSize(22);
        doc.text(COMPANY_NAME, 105, 20, { align: 'center' });
        doc.setFontSize(12);
        doc.text('Payslip', 105, 30, { align: 'center' });

        doc.setFontSize(10);
        doc.text(`Payslip ID: ${record.id}`, 14, 45);
        doc.text(`Period: ${record.month} ${record.year}`, 14, 50);
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 55);

        doc.text(`Employee Name: ${record.employeeName}`, 120, 45);
        doc.text(`Employee ID: ${record.employeeId}`, 120, 50);

        // Earnings Table
        autoTable(doc, {
            startY: 65,
            head: [['Description', 'Amount']],
            body: [
                ['Basic Salary', record.basicSalary.toLocaleString()],
                ['Allowances', record.allowances.toLocaleString()],
            ],
            theme: 'striped',
            headStyles: { fillColor: [66, 66, 66] }
        });

        // Deductions Table
        autoTable(doc, {
            startY: doc.lastAutoTable.finalY + 10,
            head: [['Deductions', 'Amount']],
            body: [
                ['Total Deductions', record.deductions.toLocaleString()],
                // Ideally this would list individual deductions if available in the record
            ],
            theme: 'striped',
            headStyles: { fillColor: [180, 50, 50] }
        });

        // Net Salary
        const finalY = doc.lastAutoTable.finalY + 15;
        doc.setFillColor(240, 240, 240);
        doc.rect(14, finalY, 182, 10, 'F');
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text('Net Salary', 20, finalY + 7);
        doc.text(`Rs. ${record.netSalary.toLocaleString()}`, 190, finalY + 7, { align: 'right' });

        // Footer
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.text('This is a computer-generated document and needs no signature.', 105, 280, { align: 'center' });
        doc.text(`Generated by ${APP_NAME}`, 105, 285, { align: 'center' });

        if (isPreview) {
            return doc.output('bloburl').toString(); // For preview in iframe
        } else {
            doc.save(`Payslip_${record.employeeName}_${record.month}_${record.year}.pdf`);
        }
    },

    generateReport: (title: string, data: any[], columns: string[], isPreview: boolean = false): string | void => {
        const doc = new jsPDF() as jsPDFWithAutoTable;

        // Header
        doc.setFontSize(18);
        doc.text(COMPANY_NAME, 14, 20);
        doc.setFontSize(14);
        doc.text(title, 14, 30);
        doc.setFontSize(10);
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 38);

        // Table
        autoTable(doc, {
            startY: 45,
            head: [columns],
            body: data.map(item => Object.values(item)),
            theme: 'grid',
            headStyles: { fillColor: [66, 66, 66] }
        });

        if (isPreview) {
            return doc.output('bloburl').toString();
        } else {
            doc.save(`${title.replace(/\s+/g, '_')}_Report.pdf`);
        }
    }
};
